Repository cyder/emoji.best, pull requests merged in 2018-06, with the labels that each got.

#30 20 signin api
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/user_sessions_controller.rb
  app/views/api/v1/errors/email.json.jb
  app/views/api/v1/errors/incorrect.json.jb
  app/views/api/v1/errors/param.json.jb
  app/views/api/v1/user_sessions/create.json.jb
  config/routes.rb
  doc/api/v1/user_sessions.md
  doc/api/v1/users.md
  spec/requests/api/v1/user_sessions_spec.rb
Labels: question, wait for review

#33 絵文字を検索できるようにした
  app/controllers/api/v1/search_controller.rb
  app/models/emoji.rb
  app/models/tag.rb
  app/views/api/v1/emojis/_emoji.json.jb
  app/views/api/v1/search/index.json.jb
  config/routes.rb
  doc/api/emoji.md
  doc/api/search.md
  doc/api/user.md
  doc/api/v1/search.md
  spec/requests/api/v1/search_spec.rb
Labels: review complete

#42 絵文字を検索できないバグを修正
  app/controllers/api/v1/search_controller.rb
Labels: review complete

#51 rubocopの設定変更
  .rubocop.yml
  app/models/emoji.rb
  app/models/user.rb
Labels: rails, wait for review

#44 ログアウト用のAPIを実装
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/user_sessions_controller.rb
  app/models/user.rb
  app/views/api/v1/user_sessions/destroy.json.jb
  config/routes.rb
  doc/api/v1/user_sessions.md
  spec/requests/api/v1/user_sessions_spec.rb
Labels: wait for review

#45 Emojiの一覧表示
  app/javascript/app/components/emoji-list.jsx
  app/javascript/app/components/emoji.jsx
  app/javascript/app/components/header.jsx
  app/javascript/app/components/shapes/emoji-list.jsx
  app/javascript/app/components/shapes/emoji.jsx
  app/javascript/app/containers/app.jsx
  app/javascript/app/redux/configure-store.jsx
  app/javascript/app/redux/modules/reducer.jsx
Labels: review complete

#58 emojiをアップロードできるようにする。
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/emojis_controller.rb
  app/models/emoji.rb
  app/uploaders/emoji_uploader.rb
  app/views/api/v1/emojis/_emoji.json.jb
  app/views/api/v1/emojis/create.json.jb
  config/initializers/carrierwave.rb
  config/routes.rb
  db/migrate/20180611125543_change_image_column_to_emoji.rb
  db/schema.rb
  doc/api/emoji.md
  doc/api/v1/emoji.md
  doc/api/v1/search.md
  spec/factories/emojis.rb
  spec/fixtures/images/indian.png
  spec/requests/api/v1/emoji_spec.rb
Labels: rails, wait for review

#53 emojiの一覧表示（ロジック）
  app/javascript/app/actions/emojis.jsx
  app/javascript/app/api/index.jsx
  app/javascript/app/app.jsx
  app/javascript/app/constants/emojis.jsx
  app/javascript/app/containers/app.jsx
  app/javascript/app/reducers/emojis.jsx
  app/javascript/app/reducers/index.jsx
  app/javascript/app/redux/configure-store.jsx
  app/javascript/app/redux/modules/reducer.jsx
  app/javascript/app/sagas/emojis.jsx
  app/javascript/app/sagas/index.jsx
  app/javascript/app/store.jsx
  db/seeds.rb
  package.json
  yarn.lock
Labels: react, review complete

#54 emoji検索のページング処理
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/search_controller.rb
  app/models/access_token.rb
  app/models/emoji.rb
  app/models/user.rb
  app/views/api/v1/search/index.json.jb
  doc/api/search.md
  doc/api/v1/search.md
  spec/requests/api/v1/search_spec.rb
Labels: rails, wait for review

#56 アクセストークンの更新を行う。
  app/models/access_token.rb
Labels: rails, wait for review

#72 emojiの表示デザインを作成
  .eslintrc
  app/javascript/app/app.jsx
  app/javascript/app/components/css/main.css
  app/javascript/app/components/css/normalize.css
  app/javascript/app/components/emoji-list.jsx
  app/javascript/app/components/emoji.jsx
  app/javascript/app/components/shapes/emoji.jsx
  app/views/app/index.html.erb
  package-lock.json
  package.json
  yarn.lock
Labels: react, review complete

#73 プロフィール表示
  app/controllers/api/v1/user_sessions_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/models/emoji.rb
  app/models/user.rb
  app/views/api/v1/users/_user.json.jb
  app/views/api/v1/users/show.json.jb
  config/routes.rb
  doc/api/user.md
  doc/api/v1/user_sessions.md
  doc/api/v1/users.md
  spec/requests/api/v1/users_spec.rb
Labels: rails, wait for review

#75 キーワード検索できるようにする
  app/javascript/app/actions/emojis.jsx
  app/javascript/app/api/index.jsx
  app/javascript/app/components/emoji-list.jsx
  app/javascript/app/components/header.jsx
  app/javascript/app/components/search-form.jsx
  app/javascript/app/components/shapes/emoji-list.jsx
  app/javascript/app/constants/emojis.jsx
  app/javascript/app/containers/app.jsx
  app/javascript/app/reducers/emojis.jsx
  app/javascript/app/sagas/emojis.jsx
Labels: react, wait for review

#71 EmojiをZipでダウンロードする
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/download_controller.rb
  app/models/download_log.rb
  config/routes.rb
  doc/api/download_log.md
  doc/api/v1/donwlod.md
  spec/requests/api/v1/donwlod_spec.rb
Labels: rails, wait for review

#74 検索を充実化
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/search_controller.rb
  app/models/emoji.rb
  app/models/tag.rb
  app/views/api/v1/search/index.json.jb
  doc/api/search.md
  doc/api/v1/search.md
  spec/requests/api/v1/search_spec.rb
Labels: rails, wait for review

#89 emoji名を英数字に限定
  app/models/emoji.rb
  spec/models/emoji_spec.rb
Labels: rails, wait for review

#86 アイコンの導入
  app/javascript/app/components/emoji.jsx
  package.json
  yarn.lock
Labels: react, wait for review

#80 emojiを並び替え
  app/javascript/app/actions/emojis.jsx
  app/javascript/app/api/index.jsx
  app/javascript/app/components/emoji-list.jsx
  app/javascript/app/components/header.jsx
  app/javascript/app/components/search-form.jsx
  app/javascript/app/components/shapes/emoji-list.jsx
  app/javascript/app/containers/app.jsx
  app/javascript/app/reducers/emojis.jsx
  app/javascript/app/sagas/emojis.jsx
Labels: react, review complete

#77 ログイン / 新規登録のポップアップデザイン
  app/assets/images/logo.png
  app/javascript/app/actions/popup-manager.jsx
  app/javascript/app/components/css/popup.jsx
  app/javascript/app/components/header.jsx
  app/javascript/app/components/navigation.jsx
  app/javascript/app/components/popup-manager.jsx
  app/javascript/app/components/search-form.jsx
  app/javascript/app/components/sign-in-popup.jsx
  app/javascript/app/components/sign-up-popup.jsx
  app/javascript/app/constants/popup-manager.jsx
  app/javascript/app/containers/app.jsx
  app/javascript/app/reducers/index.jsx
  app/javascript/app/reducers/popup-manager.jsx
  config/webpacker.yml
Labels: react, review complete

#82 only_full_group_byのエラーが出ないようにした
  app/models/emoji.rb
  spec/requests/api/v1/search_spec.rb
Labels: rails, wait for review

#90 リファクタ
  app/javascript/app/components/header.jsx
  app/javascript/app/containers/app.jsx
  app/javascript/app/containers/navigation.jsx
  app/javascript/app/containers/popup-manager.jsx
  app/javascript/app/containers/search-form.jsx
Labels: react, wait for review
