Repository cyder/emoji.best, pull requests merged in 2018-08, with the labels that each got.

#199 ダウンロードボタンをコンポーネント化
  app/javascript/app/components/atoms/buttons/circle-button.jsx
  app/javascript/app/components/atoms/icons/check.jsx
  app/javascript/app/components/emoji-detail.jsx
  app/javascript/app/components/emoji.jsx
  app/javascript/app/components/molecules/buttons/download-checkbox.jsx
  app/javascript/app/constants/styles/color.jsx
Labels: react, wait for review

#200 横長の絵文字のリサイズ方法をSlackに合わせた
  app/javascript/app/components/download-cart.jsx
  app/javascript/app/components/emoji-detail-info.jsx
  app/javascript/app/components/emoji.jsx
  app/javascript/app/components/shapes/emoji.jsx
  app/javascript/app/components/upload-emoji.jsx
  app/uploaders/emoji_uploader.rb
  app/views/api/v1/emojis/_emoji.json.jb
Labels: rails, react, wait for review

#209 typoの修正
  app/javascript/app/components/emoji-error.jsx
  app/javascript/app/components/emoji-list.jsx
Labels: react, wait for review

#206 emoji画像のコンポーネントを統一
  app/javascript/app/components/atoms/emojis/emoji-img.jsx
  app/javascript/app/components/download-cart.jsx
  app/javascript/app/components/emoji-detail-info.jsx
  app/javascript/app/components/emoji.jsx
  app/javascript/app/components/upload-emoji.jsx
Labels: react, wait for review

#210 titleタグの変更
  app/javascript/app/components/app.jsx
  app/javascript/app/components/atoms/head/head-title.jsx
  app/javascript/app/containers/emoji-detail-popup.jsx
  app/javascript/app/containers/sign-in-popup.jsx
  app/javascript/app/containers/sign-up-popup.jsx
  app/javascript/app/containers/upload-popup.jsx
  package.json
  yarn.lock
Labels: react, wait for review

#207 metaタグの変更
  app/controllers/app_controller.rb
  app/controllers/emojis_controller.rb
  app/helpers/application_helper.rb
  app/models/emoji.rb
  app/uploaders/emoji_uploader.rb
  config/routes.rb
Labels: rails, wait for review

#220 url-search-params-polyfillを追加
  app/javascript/app/components/app.jsx
  package.json
  yarn.lock
Labels: bug, react, wait for review

#213 APIをリファクタ
  app/javascript/app/api/base.js
  app/javascript/app/api/constans.js
  app/javascript/app/api/emoji.js
  app/javascript/app/api/index.js
  app/javascript/app/api/index.jsx
  app/javascript/app/api/tag.js
  app/javascript/app/api/user.js
  app/javascript/app/reducers/download-cart.jsx
  app/javascript/app/sagas/emoji.jsx
  app/javascript/app/sagas/emojis.jsx
  app/javascript/app/sagas/myself.jsx
  app/javascript/app/sagas/upload-emoji.jsx
Labels: react, wait for review

#216 サブタイトルと説明を変更
  app/assets/images/ogp.png
  app/helpers/application_helper.rb
  app/javascript/app/components/atoms/head/head-title.jsx
  app/javascript/app/containers/header.jsx
  app/models/emoji.rb
Labels: wait for review

#202 button componentの統一
  app/javascript/app/components/atoms/buttons/button.jsx
  app/javascript/app/components/atoms/buttons/circle-button.jsx
  app/javascript/app/components/atoms/buttons/fill-button.jsx
  app/javascript/app/components/atoms/buttons/link-button.jsx
  app/javascript/app/components/atoms/icons/check.jsx
  app/javascript/app/components/atoms/icons/download.jsx
  app/javascript/app/components/atoms/icons/facebook.jsx
  app/javascript/app/components/atoms/icons/google.jsx
  app/javascript/app/components/atoms/icons/twitter.jsx
  app/javascript/app/components/css/popup.jsx
  app/javascript/app/components/download-cart.jsx
  app/javascript/app/components/emoji-detail.jsx
  app/javascript/app/components/molecules/buttons/label-and-icon-button.jsx
  app/javascript/app/components/sns-oauth.jsx
  app/javascript/app/constants/styles/color.jsx
  app/javascript/app/containers/sign-in-popup.jsx
  app/javascript/app/containers/sign-up-popup.jsx
  app/javascript/app/containers/upload-popup.jsx
Labels: react, wait for review

#225 Fix typo
  app/javascript/app/api/constants.js
  app/javascript/app/api/emoji.js
  app/javascript/app/api/tag.js
  app/javascript/app/api/user.js
Labels: wait for review

#223 CDNサーバを経由するよう設定
  .env.sample
  Gemfile
  Gemfile.lock
  config/initializers/carrierwave.rb
Labels: rails, wait for review
